let fruta = ["Mango", "Piña", "Manzana", "Durazno", "Rábano", "Banano", "Naranja", "Mandarina", "Uva", "Mora"]
let animales = ["caballo", "vaca", "jirafa", "conejo", "oveja"]
let nombres = ["David1", "David2", "Steban", "Gerson", "Miguel"]
let tecnologias = ["ADSO", "ADSI", "PDS", "AD", "TI"]
let telefonos = [1111111111, 2222222222, 3333333333, 4444444444, 5555555555]

// FOR EACH

// fruta.forEach(fruta2=>{
//     console.log(fruta2);
// })
// animales.forEach(animales2=>{
//     console.log(animales2);
// })

// nombres.forEach(nombres2=>{
//     console.log(nombres2);
// })

// tecnologias.forEach(tecnologias2=>{
//     console.log(tecnologias2);
// })

// telefonos.forEach(telefonos2=>{
//     console.log(telefonos2);
// })

// FOR OF

// for(let fruta2 of fruta){
//     console.log(`fruta2: ${fruta2}`)
// }

// for(let animales2 of animales){
//     console.log(`animales2: ${animales2}`)
// }

// for(let nombres2 of nombres){
//     console.log(`nombres2: ${nombres2}`)
// }

// for(let tecnologias2 of tecnologias){
//     console.log(`tecnologias2: ${tecnologias2}`)
// }

// for(let telefonos2 of telefonos){
//     console.log(`telefonos2: ${telefonos2}`)
// }

// WHILE 

// while (fruta.length>0){
//     const fruta4 = fruta.shift();
//     console.log(fruta4);
// }

// while (animales.length>0){
//     const animales2 = animales.shift();
//     console.log(animales2);
// }

// while (nombres.length>0){
//     const nombres2 = nombres.shift();
//     console.log(nombres2);
// }

// while (tecnologias.length>0){
//     const tecnologias2 = tecnologias.shift();
//     console.log(tecnologias2);
// }

// while (telefonos.length>0){
//     const telefonos2 = telefonos.shift();
//     console.log(telefonos2);
// }